name: Check latest version from nearcore & AutoPublish NearUp

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: nearup
    steps:
      - uses: actions/checkout@v3
      - name: Fetch And Update        
        run: chmod +x scripts/CheckAndUpdate.sh
          
          
          
