name: Check latest version from nearcore & AutoPublish NearUp

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: nearup
    env:
       Version: curl -sL https://api.github.com/repos/near/nearcore/releases/latest | jq -r ".tag_name"
    steps:
      - uses: actions/checkout@v3
      - name: Fetch And Update        
        run: curl -sL https://api.github.com/repos/near/nearcore/releases/latest | jq -r ".tag_name" > nearuplib/VERSION
      - name: Fetch And Update        
        run: echo "$version"
      - uses: EndBug/add-and-commit@v9 
        with: 
          add: 'VERSION --force'
          message: "Bump version $version"
          
          
          
