name: Check latest version from nearcore & AutoPublish NearUp

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: nearup
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.MYGITHUB_TOKEN }}
      - name: Fetch And Update        
        run: curl -sL https://api.github.com/repos/near/nearcore/releases/latest | jq -r ".tag_name" > nearuplib/VERSION
      - name: Get Version
        id: get_version
        run: echo ::set-output name=version::$(curl -sL https://api.github.com/repos/near/nearcore/releases/latest | jq -r ".tag_name")
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Commit latest release version
        env: 
         GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        if: steps.git-check.outputs.modified == 'true'
        uses: EndBug/add-and-commit@v9 
        with: 
          add: 'nearuplib/VERSION --force'
          message: "Bump version ${{steps.get_version.outputs.version}}"

          
          
          
