name: Check latest version from nearcore & AutoPublish NearUp

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: nearup
    steps:
      - uses: actions/checkout@v3
      - name: Fetch And Update        
        run: curl -sL https://api.github.com/repos/near/nearcore/releases/latest | jq -r ".tag_name" > nearuplib/VERSION
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          VERSION: curl -sL https://api.github.com/repos/near/nearcore/releases/latest | jq -r ".tag_name"
      - name: Fetch And Update        
        run: echo "${VERSION}"
      - uses: EndBug/add-and-commit@v9 
        with: 
          add: 'VERSION --force'
          message: "Bump version ${VERSION}"
          
          
          
