name: Check latest version from nearcore & AutoPublish NearUp

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: nearup
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.MYGITHUB_TOKEN }}
		 
      - name: Update script right
        run: chmod +x scripts/updateVersion.sh 
		
      - name: Fetch And Update        
        run: curl -sL https://api.github.com/repos/near/nearcore/releases | jq -r 'first | .tag_name' > nearuplib/latestCheckedVersion.txt
		
	  - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
		
      - name: Get Type
	    if: steps.git-check.outputs.modified == 'true'
        id: get_version
        run: echo ::set-output name=prerelease::$(curl -sL https://api.github.com/repos/near/nearcore/releases | jq -r 'first | .prerelease')
      
	  - name: Set Type
		if: steps.git-check.outputs.modified == 'true' && steps.git-get_version.outputs.prerelease == 'true'
		id: get_version
	    run: scripts/updateVersion.sh $(cat nearuplib/VERSION) bug > nearuplib/VERSION
		
		- name: Set Type
		if: steps.git-check.outputs.modified == 'true' && steps.git-get_version.outputs.prerelease == 'false'
		id: get_version
	    run: scripts/updateVersion.sh $(cat nearuplib/VERSION) bug > nearuplib/VERSION      
	  
      - name: Commit latest release version
        env: 
         GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        if: steps.git-check.outputs.modified == 'true'
        uses: EndBug/add-and-commit@v9 
        with: 
          add: 'nearuplib/VERSION --force'
          message: "Bump version ${{steps.get_version.outputs.version}}"
