name: Check latest version from nearcore & AutoPublish NearUp

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: nearup
    steps:
      - uses: actions/checkout@v3
      - name: Add right       
        run: chmod +x scripts/CheckAndUpdate.sh
      - name: Fetch And Update        
        run: bash scripts/CheckAndUpdate.sh
      - uses: EndBug/add-and-commit@v9 
        with: 
          author_name: "Nearup Auto"
          author_email: "davletuner@protonmail.com"
          add: 'near-nearcore-latest.txt --force'
          message: "AutoUpdated"
          
          
          
