  
name: Build and Publish
on:
  push:
   branches:
      - master
jobs:
  build_binary:
    runs-on: ubuntu-latest
    environment: nearup

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2020-03-19
        
    - uses: actions/checkout@master
    
    - uses: chrislennon/action-aws-cli@v1.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
    - name: Setup python
      uses: actions/setup-python@v2
      with:
            python-version: 3.9
            
    - name: Setup Tox
      run: pip3 install --user tox
      
    - name: Setup boto3
      run: pip install boto3
      
    - name: Build and release pypi package  
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      run: ~/.local/bin/tox -e build && ~/.local/bin/tox -e release
      
    - name: Build and release docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: scripts/docker-release.sh
      
    - name: Publish files to S3 - Guildnet
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEPLOY_VERSION: ${{ secrets.DEPLOY_VERSION }} 
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
      run: scripts/binary-release.sh
      
    - name: Publish files to S3 - Testnet
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEPLOY_VERSION: stable
        SSH_USER: ${{ secrets.SSH_USER_TESTNET }}
        SSH_HOST: ${{ secrets.SSH_HOST_TESTNET }}
        SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY_TESTNET }}
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY_TESTNET }}
      run: scripts/binary-release.sh
